<?php

namespace WikiLeaksEmailDump\Obtainer;

use \ArrayAccess;

/**
* Contract for anything which fires a Web Request and 
*   returns the Response for that Request
*/
interface WebRequesterContract 
{
  
  /**
  * Constructs a WebRequester with requests to URLs that are 
  *   generated by the provided exhaustible generator
  * @param Closure $generator An exhaustible generator that generates URLs 
  *   to request from
  */
  public static function fromGenerator(Closure $generator);
  
  /**
  * Fires the request/s
  */
  public function request();
  
  /**
  * Obtains the responses from the request/s
  * @returns ArrayAccess A list of index-mapped string responses
  */
  public function getResponses(): ArrayAccess;
  
}